### ISSUE TITLE
Question about range-doppler heatmap

### ISSUE THREAD

**Issue by chenxin926** [ibaiGorordo/AWR1642-Read-Data-Python-#36]
Hi my friend
Thank you for uploading the code, it is very useful
There is something wrong with the Doppler heat map when I run the code. Could you please advise me if there is something wrong with the.cfg file I configured and I can only use if np.max(RangeDoppler) >The picture will not appear until 30000 is changed to 50000, otherwise the picture will not be available. Could you please tell me the reason? Thank  you!
![1 (1)](https://user-images.githubusercontent.com/56642580/116114979-7cba2a00-a6ec-11eb-9e05-bdc2489abd84.png)
![1 (2)](https://user-images.githubusercontent.com/56642580/116115012-86dc2880-a6ec-11eb-8f16-d9a5bc195798.png)
![1 (3)](https://user-images.githubusercontent.com/56642580/116115036-8f346380-a6ec-11eb-8a00-2211c4db4df8.png)
![1 (4)](https://user-images.githubusercontent.com/56642580/116115065-965b7180-a6ec-11eb-87bf-76c1da2b22dc.png)
![1 (5)](https://user-images.githubusercontent.com/56642580/116115134-a96e4180-a6ec-11eb-8abd-5ade50dc7307.png)

**Comment by ibaiGorordo** [comment]
Hi, if that configuration works well with the demo visualizer, it is probably a problem with the implementation. Actually that if statement should not be there but I put it there becaue I was not sure why the range heatmap data was bad in some cases (it looks like in your case it is that way for all frames).

I am not sure if it will make any difference, but if you can update the firmware to the SDK3, then try my other repository (https://github.com/ibaiGorordo/AWR1843-Read-Data-Python-MMWAVE-SDK-3-), which is the version I tested for the heatmap plot.

Otherwise, you might want to check at the code in this repository (https://github.com/m6c7l/pymmw) as it seems that they are able to plot the heatmap correctly (I am budy with other projects now, so I cannot try to fix this implementation).

**Comment by chenxin926** [comment]
Thank you for your reply. I will try to change your 1843 code to 1642 code, because the number of antennas is different. Thanks again
