### ISSUE TITLE
DriverVitalSignLab

### ISSUE THREAD

**Issue by MariadeCarlos** [ibaiGorordo/AWR1642-Read-Data-Python-#43]
Kaixo Ibai! Eskerrik asko zure kodigoa zabaltzeagatik. 

I am trying to work with your code but I do not receive any data from your radar after using the cfg file for the vital sign sensing, and I can therefore not see anything in the GUI (It does not even open) 

I would appreciate it if you could help me in any way. 

I have flashed the device (AWR1642) with the SDK 2.01

**Comment by ibaiGorordo** [comment]
Kaixo, eskerrik asko!

It has been a while since I used so I might be wrong. For the vital sign demo you will have to flash the binary that is included in the vital sign lab of the [automotive toolbox](https://dev.ti.com/tirex/explore/node?node=AFeCagqbt7.hu2lHOXE4eA__AocYeEd__LATEST) (the one in the industrial toolbox might work but I am not sure).

However, I am not sure if this code will work with the latest version or if something has changed lately.

**Comment by MariadeCarlos** [comment]
Yes that was it! 
I tried it on automotive toolbox 2.5 and it works 
Thanks a lot

**Comment by Daya-AWR1642** [comment]
> Yes that was it! I tried it on automotive toolbox 2.5 and it works Thanks a lot

Hi!!
I'm also facing same problem can you please help me to resolve it

**Comment by mjk1376** [comment]
hello can anyone help me solve same problem. i can't find file in that link
